apiVersion: apps/v1
kind: Deployment
metadata:
  name: digimon-pg-schedule-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digimon-pg-schedule-app
  template:
    metadata:
      labels:
        app: digimon-pg-schedule-app
    spec:
      containers:
        - name: digimon-pg-schedule-container
          image: kingpiggy/digimon-pg-dev-schedule:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_PROFILES_INCLUDE
              value: core,dev
