apiVersion: v1
kind: Service
metadata:
  name: digimon-pg-dev-schedule-service
  namespace: dev
spec:
  selector:
    app: digimon-pg-schedule-app
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: NodePort
